### ISSUE TITLE
Improve the description of `refactor` commit type

### ISSUE THREAD

**Issue by YoPoulou** [ejpcmac/git-z#41]
In the `git-z.toml` file describing the different type of commit, the term `refactor` is defined as a tautology. Instead we could use a real definition. E.g. in wikipedia : "A code refactor is a proccess of restructuring existint source code without changing its external behavior". 

Source : https://en.m.wikipedia.org/wiki/Code_refactoring

**Comment by ejpcmac** [comment]
I’m going for :

> restructure the code without changing its external behaviour
